---
functional:
  - Требование Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Требование Пользователь должен иметь возможность фильтровать товары
  - Требование Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Требование Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Требование Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Требование Сайт должен быть безопасным и защищать данные пользователя
  - Требование Сайт должен иметь мобильную версию
  - Требование Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Требование Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Требование Сайт должен быть доступен на различных устройствах
implicit:
- При поиске и фильтрации товаров интерфейс должен быть интуитивно понятным
- Страницы с подробной информацией о товаре должны включать такие данные, как описание, фотографии, цена и отзывы
- Корзина должна сохранять товары, даже если пользователь обновляет страницу или закрывает браузер
- В корзине должна быть информация о стоимости товаров, общей сумме и возможности изменения количества товаров или удаления их
