---
functional:
  - Требование Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Требование Пользователь должен иметь возможность фильтровать товары
  - Требование Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Требование Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Требование Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Требование Сайт должен быть безопасным и защищать данные пользователя
  - Требование Сайт должен иметь мобильную версию
  - Требование Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Требование Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Требование Сайт должен быть доступен на различных устройствах
implicit:
  - Требование Корзина должна сохраняться в сессии браузера для удобства пользователя
  - Требование Современность и эстетика дизайна магазина
  - Требование Качественные изображения и визуальная презентация товаров

